@host = http://localhost:4004
@catalog = {{host}}/odata/v4/catalog

POST {{catalog}}/Tickets
Content-Type: application/json

{
    "ticketNumber": "INC#",
    "subject" : "Invoicing doesn't work!",
    "description" : "Starting 3PM today, we can't perform invoicing for all types of deliveries. We need resolution!",
    "priority" : "HIGH",
    "category" : [ { "name" : "SAP-SD" } ],
    "agent" : [{ "name" : "Alyssa Reyes" }],
    "comments" : [
        { 
            "text" : "Hi Alyssa, I'm directly putting you in Asignee since you worked on this last week."
        }
    ]
}