@host = http://localhost:4004
@catalog = {{host}}/odata/v4/catalog

POST {{catalog}}/Tickets
Content-Type: application/json

{
    "ticketNumber": "INC#",
    "subject" : "Invoicing doesn't work!",
    "description" : "Starting 3PM today, we can't perform invoicing for all types of deliveries. We need resolution!",
    "priority" : "HIGH",
    "category" : { "name" : "SAP-SD" },
    "agent" : { "ID" : "7f8c2a64-6d4e-4d5c-9f3a-12b8a4c9e101" },
    "comments" : [
        { 
            "text" : "Hi Alyssa, I'm directly putting you in Asignee since we already had a call on this earlier."
        }
    ]
}